server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
# We can add a few more properties to control max Redis connections etc.
  boot:
    health:
      status:
        order: DOWN,UP
management:
  health:
    shutdown:
      enabled: true
logging:
  level:
    root: INFO
    com.processor.taskProcessor.service.TaskService: DEBUG
    com.processor.taskProcessor.service.MockTaskProcessor: DEBUG
    com.processor.taskProcessor.service.PatternMatchService: DEBUG
async:
  executor:
    core-pool-size: 2
    max-pool-size: 10
    queue-capacity: 25
taskprocessor:
  number-of-loops: 8 # Number of mock loops. Each loop waits 1000ms. Defaults to 0
  max-typos:   # Empty or <0 defaults to length of pattern-1